replicaCount: 1

image:
  repository: lieusolocode/evofast-frontend-aks
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

ingress:
  enabled: true
  ingressClassName: nginx
  hosts:
    - host: evofast-dev.solocode.click
      paths:
        - path: /
          pathType: Prefix
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /

env:
  NEXTAUTH_URL: "https://evofast-dev.solocode.click"
