name: Build-Push Docker Image 

on:
  push:
    branches:
      - 'develop-aks'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver: docker-container
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.SOLOCODE_USERNAME }}
          password: ${{ secrets.SOLOCODE_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/arm64
          push: true
          tags: ${{ secrets.SOLOCODE_USERNAME }}/evofast-frontend-aks:latest

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'
      - name: Setup Helm
        uses: azure/setup-helm@v3
        with:
          version: 'latest'

      - name: Configure kubeconfig
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        run: |
          echo "$KUBE_CONFIG_DATA" | base64 --decode > $HOME/.kube/config

      - name: Helm upgrade/install
        run: |
          helm upgrade --install evofast-frontend ./helm-chart/evofast-frontend \
            --set image.tag=latest \
            --set image.repository=${{ secrets.SOLOCODE_USERNAME }}/evofast-frontend-aks