name: Build-Push Docker Image 

on:
  push:
    branches:
      - 'develop-aks'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      # -
      #   name: Checkout
      #   uses: actions/checkout@v3
        
      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v2
      #   with:
      #     driver: docker-container
      # -
      #   name: Login to DockerHub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.SOLOCODE_USERNAME }}
      #     password: ${{ secrets.SOLOCODE_TOKEN }}

      - name: Set IMAGE_TAG
        run: echo "IMAGE_TAG=${{ github.sha }}" >> $GITHUB_ENV

      # -
      #   name: Build and push
      #   uses: docker/build-push-action@v3
      #   with:
      #     context: .
      #     platforms: linux/arm64
      #     push: true
      #     tags: ${{ secrets.SOLOCODE_USERNAME }}/evofast-frontend-aks:${{ env.IMAGE_TAG }} 

      - name: Checkout Helm chart repo
        uses: actions/checkout@v3
        with:
          repository: EvofastEnglish/evofast-frontend-chart
          token: ${{ secrets.GH_TOKEN }}
          path: evofast-frontend-chart

      - name: Install yq
        run: |
            sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq
            sudo chmod +x /usr/bin/yq
          
      - name: Update values.yaml with new image tag
        run: |
            cd evofast-frontend-chart
            yq eval '.image.tag = strenv(IMAGE_TAG)' -i values.yaml

      - name: Create Pull Request to Helm chart repo
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GH_TOKEN }}
          path: evofast-frontend-chart
          commit-message: "chore: update image tag to ${{ env.IMAGE_TAG }}"
          title: "Update image tag to ${{ env.IMAGE_TAG }}"
          body: |
            This PR was automatically created by GitHub Actions after pushing a new Docker image.
              New tag: `${{ env.IMAGE_TAG }}`
          branch: update-image-${{ github.sha }}
          base: main
          merge: true
          merge-method: squash
          

      # - name: Setup kubectl
      #   uses: azure/setup-kubectl@v3
      #   with:
      #     version: 'latest'

      # - name: Setup Helm
      #   uses: azure/setup-helm@v3
      #   with:
      #     version: 'latest'

      # - name: Decode and set KUBECONFIG
      #   run: |
      #     mkdir -p $HOME/.kube
      #     echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 --decode > $HOME/.kube/config
      #     echo "KUBECONFIG=$HOME/.kube/config" >> $GITHUB_ENV

      # - name: Helm upgrade/install
      #   run: |
      #     helm upgrade --install evofast-frontend ./helm-chart/evofast-frontend \
      #       --set image.repository=${{ secrets.SOLOCODE_USERNAME }}/evofast-frontend-aks \
      #       --set image.tag=${{ env.IMAGE_TAG }} \
      #       --set image.pullPolicy=Always